aliases:
  - &upgrade-git
    name: Update Git
    command:  |
      git --version
      sudo apt-get update
      sudo apt-get install \
        build-essential flex bison \
        libreadline6-dev zlib1g-dev \
        libssl-dev \
        libcurl4-gnutls-dev \
        libexpat1-dev \
        tcl tk \
        tcl-dev gettext \
        asciidoc \
        docbook2x

      wget https://www.kernel.org/pub/software/scm/git/git-2.13.0.tar.gz
      tar -xvzf git-2.13.0.tar.gz
      cd git-2.13.0
      sudo ./configure
      sudo make && sudo make install
      git --version

  - &setup
    name: Setup
    command: node ./install.js
    when: always

  - &ios-cordova
    name: Install Cordova
    command:  |
      npm install -g cordova@8.1.2
      cordova telemetry off

  - &android-cordova
    name: Install Cordova
    command:  |
      sudo npm install -g cordova@8.1.2
      sudo cordova telemetry off

  - &install-ant
    name: Install Ant
    command: brew install ant

  - &install-sfdx
    name: Install SFDX
    command: |
      if [[ "$OSTYPE" == "linux-gnu" ]]; then
        sudo npm install -g sfdx-cli@6
        sudo chown -R `whoami` $HOME/.config/
      else 
        npm install -g sfdx-cli@6
      fi
    when: always

linux: &linux
  working_directory: ~/SalesforceMobileSDK-Package
  docker:
    - image: circleci/android:api-28-node
  environment:
    - TERM: "dumb"
    - GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'

mac: &mac
  working_directory: ~/SalesforceMobileSDK-Package
  macos:
    xcode: "10.2.1"
  shell: /bin/bash --login -eo pipefail

version: 2
jobs:
  forcedroid:
    <<: *linux
    steps:
      - checkout
      - run: *upgrade-git
      - run: *setup
      - run:
          name: Building all android native templates
          command:  ./test/test_force.js --exit-on-failure --cli=forcedroid
          when: always

  forcedroid-sfdx:
    <<: *linux
    steps:
      - checkout
      - run: *upgrade-git
      - run: *setup
      - run: *install-sfdx
      - run:
          name: Building all android native templates with SFDX
          command: ./test/test_force.js --exit-on-failure --cli=forcedroid --use-sfdx
          when: always

  forcehybrid-android:
    <<: *linux
    steps:
      - checkout
      - run: *upgrade-git
      - run: *setup
      - run: *android-cordova
      - run:
          name: Building all android hybrid templates
          command: ./test/test_force.js --exit-on-failure --cli=forcehybrid --os=android
          when: always

  forcehybrid-android-sfdx:
    <<: *linux
    steps:
      - checkout
      - run: *upgrade-git
      - run: *setup
      - run: *android-cordova
      - run: *install-sfdx
      - run:
          name: Building all android hybrid templates with SFDX
          command: ./test/test_force.js --exit-on-failure --cli=forcehybrid --os=android --use-sfdx
          when: always

  forcereact-android:
    <<: *linux
    steps:
      - checkout
      - run: *upgrade-git
      - run: *setup
      - run:
          name: Building all android react native templates
          command: ./test/test_force.js --exit-on-failure --cli=forcereact --os=android
          when: always

  forcereact-android-sfdx:
    <<: *linux
    steps:
      - checkout
      - run: *upgrade-git
      - run: *setup
      - run: *install-sfdx
      - run:
          name: Building all android react native templates with SFDX
          command: ./test/test_force.js --exit-on-failure --cli=forcereact --os=android --use-sfdx
          when: always

  forceios:
    <<: *mac
    steps:
      - checkout
      - run: *setup
      - run: *install-ant
      - run:
          name: Building all ios native templates
          command:  ./test/test_force.js --exit-on-failure --cli=forceios
          when: always

  forceios-sfdx:
    <<: *mac
    steps:
      - checkout
      - run: *setup
      - run: *install-ant
      - run: *install-sfdx
      - run:
          name: Building all ios native templates with SFDX
          command: ./test/test_force.js --exit-on-failure --cli=forceios --use-sfdx
          when: always

  forcehybrid-ios:
    <<: *mac
    steps:
      - checkout
      - run: *setup
      - run: *ios-cordova
      - run: *install-ant
      - run:
          name: Building all ios hybrid templates
          command: ./test/test_force.js --exit-on-failure --cli=forcehybrid --os=ios
          when: always

  forcehybrid-ios-sfdx:
    <<: *mac
    steps:
      - checkout
      - run: *setup
      - run: *ios-cordova
      - run: *install-ant
      - run: *install-sfdx
      - run:
          name: Building all ios hybrid templates with SFDX
          command: ./test/test_force.js --exit-on-failure --cli=forcehybrid --os=ios --use-sfdx
          when: always

  forcereact-ios:
    <<: *mac
    steps:
      - checkout
      - run: *setup
      - run: *install-ant
      - run:
          name: Building all ios react native templates
          command: ./test/test_force.js --exit-on-failure --cli=forcereact --os=ios
          when: always

  forcereact-ios-sfdx:
    <<: *mac
    steps:
      - checkout
      - run: *setup
      - run: *install-ant
      - run: *install-sfdx
      - run:
          name: Building all ios react native templates with SFDX
          command: ./test/test_force.js --exit-on-failure --cli=forcereact --os=ios --use-sfdx
          when: always

workflows:
  version: 2

  pr-build-all-apps:
    jobs:
      - forceios
      - forcehybrid-ios
      - forcereact-ios
      - forcedroid
      - forcehybrid-android
      - forcereact-android
      - forceios-sfdx
      - forcehybrid-ios-sfdx
      - forcereact-ios-sfdx
      - forcedroid-sfdx
      - forcehybrid-android-sfdx
      - forcereact-android-sfdx

  # Cron are on a timezone 8 hours ahead of PST
  # Build everything at ~8:30pm Sunday/Wednesday Nights
  weekly-build-all-apps:
    triggers:
      - schedule:
          cron: "30 4 * * 2,4,6"
          filters:
            branches:
              only:
                - dev
    jobs:
      - forceios
      - forcehybrid-ios
      - forcereact-ios
      - forcedroid
      - forcehybrid-android
      - forcereact-android
      - forceios-sfdx
      - forcehybrid-ios-sfdx
      - forcereact-ios-sfdx
      - forcedroid-sfdx
      - forcehybrid-android-sfdx
      - forcereact-android-sfdx
